# Generated by Django 2.2.13 on 2020-06-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200623_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='ghfjhfgjhgfjhgfjh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhghfkjfkjgf',
        ),
    ]
